#Etapa 1. Dependencias de desarrollo
FROM node:alpine as dev-dep
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

#Etapa 2. Build 
FROM node:alpine as build
WORKDIR /app
COPY --from=dev-dep /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Etapa 3. Dependencias de produccion
FROM node:alpine as prod-dep
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production 

#Etapa 4. Crear la imagen final
FROM node:alpine as prod
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=prod-dep /app/node_modules ./node_modules
CMD ["node", "dist/index.js"]

